### ISSUE TITLE
When will there be a 2019 VSIX version ?

### ISSUE THREAD

**Issue by Smurf-IV** [RickStrahl/MarkdownMonsterAddinProjectTemplate#2]

**Comment by RickStrahl** [comment]
Can you be more specific? You should be able to create an addin for Visual Studio 2019. One thing that needs to be fixed is the .NET version needs to be revved to revved for 4.7.2 due to the dependencies used.

Ok never mind :-) there are clearly problems here with the new SDK style projects, and I guess that's the real request here:

**Create Addin Template for SDK style projects**

**Comment by Smurf-IV** [comment]
> 
> 
> One thing that needs to be fixed is the .NET version needs to be revved to revved for 4.7.2 due to the dependencies used.
> 
> 

Now I understand that comment:
**Yes** updating the Requirements in the documentation to state to use either 4.7.2 or greater would be good.
**And** to also retrofit the previous VSIX plug-ins,
**And** to create a plug-in that works with Visual Studio 2019

**Comment by RickStrahl** [comment]
I've updated the extension and it works now with VS 2019. This is still an old .NET project, but it now works properly in VS 2019.

The issue actually was that the changes from the repo hadn't been pushed. The addin in the gallery was current, but the source code was not. The repo is now up to date.
